environment:
  nodejs_version: "6"
  skip_tags: false

install:
  - npm install
  - ./node_modules/.bin/webpack -p
  - npm run build

build: off

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

test: off

artifacts:
  - path: ./dist/testApp*
    name: testApp

deploy:
  - provider: GitHub
    artifact: testApp
    draft: false
    prerelease: false
    
    auth_token:
      secure: '7miOW5i28F3QTVsgMmGBI7lhkxfS2kD3DKQPhTLgTIlmROJ6lGBke1/GYTPqwCUx'
      
    on:
#     branch: master
      appveyor_repo_tag: true
#   release: wisnucAssistant-v$(appveyor_build_version)
#   description: 'Release test'
