environment:
  nodejs_version: "6"
  skip_tags: true

#  appveyor_repo_tag: true
#  release: wisnucAssistant-v$(appveyor_build_version)
#  description: 'Release test'
#  provider: GitHub
#  artifact: ./dist/"testApp Setup 1.0.0.exe"
#  draft: false
#  prerelease: false
#  auth_token:
#    secure: 938a98c742afc2ca0094a500bc0d15487b861655

install:
#  - npm install electron-prebuilt --save-dev
#  - npm install electron-builder electron-updater webpack
  - npm install
  - ./node_modules/.bin/webpack -p
  - npm run build

build: off

build_script:
#  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64 -p always
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

test: off

artifacts:
  - path: ./dist/testApp*
    name: testApp

deploy:
  - provider: GitHub
    artifact: testApp
    draft: false
    prerelease: false
    
    auth_token:
      secure: '7miOW5i28F3QTVsgMmGBI7lhkxfS2kD3DKQPhTLgTIlmROJ6lGBke1/GYTPqwCUx'
      
    on:
      branch: master
#      appveyor_repo_tag: true
    release: wisnucAssistant-v$(appveyor_build_version)
    description: 'Release test'
